# Generated by Django 4.1.7 on 2023-09-20 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_title', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examtitle',
            name='is_vip',
            field=models.BooleanField(default=False),
        ),
    ]
