# Generated by Django 4.1.7 on 2023-09-08 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_id', models.CharField(max_length=50)),
                ('part', models.IntegerField()),
                ('number', models.IntegerField()),
                ('paragraph', models.TextField(null=True)),
                ('question', models.TextField(null=True)),
                ('option1', models.TextField(null=True)),
                ('option2', models.TextField(null=True)),
                ('option3', models.TextField(null=True)),
                ('option4', models.TextField(null=True)),
                ('correct_answer', models.CharField(max_length=5)),
                ('explaination', models.TextField(null=True)),
            ],
        ),
    ]
