# Generated by Django 4.1.7 on 2023-09-11 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0003_examination_audio_url_examination_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examination',
            name='audio_url',
        ),
    ]
