# Generated by Django 4.1.7 on 2023-08-17 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firebase_id', models.CharField(max_length=255, unique=True)),
                ('avatar', models.TextField(null=True)),
                ('username', models.CharField(max_length=255)),
                ('gender', models.BooleanField(null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('is_vip', models.BooleanField(default=False)),
                ('vip_start', models.DateField(null=True)),
                ('vip_end', models.DateField(null=True)),
            ],
        ),
    ]
